🩹 Update ros control pid
ThundeRatz/travesim pull request #19
Opened 2021-03-28 20:32 UTC by LucasHaug

Então sempre apareciam essas mensagens de erro pra gente né:

![image](https://user-images.githubusercontent.com/39196309/112766985-ac411e00-8fea-11eb-8d4d-8d9a6a1f7456.png)

Fui dar uma olhada e aqueles parâmetros que a gente tava passando pro PID na verdade nem tavam sendo usados ahsuhushaushuah, aí tecnicamente o jeito de passar esses parâmetros pro `ros_control` é do jeito que fiz nessa PR. Porém é engraçado que se a gente passar as constantes de agora pro `ros_control`, o robô fica incontrolável e andando sozinho ahsuhaushuashu. Sobre isso achei essa issue [aqui](https://answers.ros.org/question/216092/problem-with-the-robot-model-collapsing/?answer=216098%3Fanswer%3D216098#post-id-216098) que fala algumas coisas legais disso. Acabei só zerando o ki e o kd, além de deixar o kp bem baixo (porque com o kp 1 mesmo ele já anda sozinho), tecnicamente acho que assim tá igual ao que tava sem mexer nisso, porque o `ros_control` só não usava o que a gente tava passando, mas desse jeito pelo menos não dá mensagem de erro lá.

E aí o que acham, a gente deixa desse jeito aqui, ou só deixa a mensagem de erro mesmo? hasuhsuahsuhauhsus

2021-03-28 22:15 UTC, lucastrschneider commented
Eu lembro de ter lido em algum lugar que quando ele da esse erro, acaba usando o valor default, e por isso não deveria ser um erro assim, mais um warning. Tem como a gnt saber quais são os valores default que ele usava antes quando a gnt não passava na mão esses parâmetros? Não sei se vale a pena configurar isso na mão assim em vez de deixar o gazebo pegar os valores que ele normalmente usa

2021-03-28 22:44 UTC, LucasHaug commented
> Eu lembro de ter lido em algum lugar que quando ele da esse erro, acaba usando o valor default, e por isso não deveria ser um erro assim, mais um warning. Tem como a gnt saber quais são os valores default que ele usava antes quando a gnt não passava na mão esses parâmetros? Não sei se vale a pena configurar isso na mão assim em vez de deixar o gazebo pegar os valores que ele normalmente usa

Justo, eh não sei também. Fui atrás disso daí que você falou e achei isso [aqui](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/b0ed38f9ecedbe929340f5e8b0aa7a457248e015/gazebo_ros_control/src/default_robot_hw_sim.cpp#L218-L219) no código do `ros_control`. Então acho que se a gente não setar, ele só não vai usar PID pra controlar as coisas mesmo.

2021-03-29 00:53 UTC, FelipeGdM requested changes
_Mundo louco esse o que vivemos_

Altamente daora a pesquisa, muito promissor refinar as configurações do modelo dessa forma

Tenho dois questionamentos a fazer, se as configurações são iguais, não seria interessante colocar em um arquivo separado que será sempre carregado?

Eu entendo que o ganho derivativo não é interessante nesse caso pela tendência à instabilidade, porém acredito que o integrativo seria interessante no nosso caso pra zerar o erro em regime. A priori, nem sei dizer se temos erro em regime, gostaria de testar o impacto do refinamento dos coeficientes do PID antes de fechar essa PR

2021-03-29 17:57 UTC, lucastrschneider commented on README.md
> +- ```drive_config_file``` - Path of simulated robot controllers config file, default "./config/motor_diff_drive.yml" if `twist_interface` is true, "./config/motor_direct_drive.yml" otherwise
Faz mais sentido algo como `controller_config_file` não? igual tá na própria descrição hahhahahha

2021-03-29 18:14 UTC, lucastrschneider commented
Eu não acho que alguém usaria a opção pra configurar os parâmetros do ros_control, nem a gente, mas já que você já fez, então tudo bem auhsuahushuhuahuah

2021-03-30 02:08 UTC, FelipeGdM requested changes

2021-03-30 02:08 UTC, FelipeGdM commented on launch/spawn_robot.launch
> +  <group if="$(eval ros_control_config_file=='')">
Como o arquivo de configuração padrão do ros_control é único, não existe necessidade dessa estrutura de if...else. Ela é necessária no caso das propriedades do controlador pois dependendo do parâmetro `twist_interface` o arquivo padrão é diferente. Dá pra simplificar bastante se trocar todos os

```xml
<arg name="ros_control_config_file" default=""/>
```

Por 

```xml
<arg name="ros_control_config_file" default="$(find vss_simulation)/config/ros_control_config.yml"/>
```

Além do valor padrão ficar mais explícito

2021-04-05 23:37 UTC, FelipeGdM submitted a review, later dismissed

2021-04-13 15:38 UTC, lucastrschneider approved these changes

2021-04-16 01:54 UTC, GabrielCosme commented on config/motor_direct_drive.yml
> -  pid:
Roda esquerda joint é meio estranho né.

2021-04-16 01:54 UTC, GabrielCosme approved these changes

2021-04-16 01:54 UTC, merged