✨ Add acceleration ramp for the keybooard script
ThundeRatz/travesim pull request #34
Opened 2021-04-18 17:33 UTC by lucastrschneider

Fala galera, eu tava brincando aqui e fiz essas mudanças no script de controle pela teclado pra deixar mais facil de usar.

Como a gente não tem um analógico que nem no controle, coloquei uma pequena rampa de aceleração na parte do teclado para evitar dele ficar dando os tranquinhos e derrapando. Além disso, limitei um pouco a velocidade máxima para o controle com o teclado também.

Tire também tudo de argparser que tava comentado, já que não estava sendo usado.

2021-04-18 17:46 UTC, LucasHaug requested changes
Niceeee sem mais robozinho dando trancos então

2021-04-18 17:46 UTC, LucasHaug commented on scripts/keyboard_node.py
> +# A vel máxima do robô é 40 rad/2
```suggestion
# A vel máxima do robô é 40 rad/s
```

2021-04-18 17:46 UTC, LucasHaug commented on scripts/keyboard_node.py
> +            txt = "Linear: {} Angular: {}".format(int(axis[1]*SCALE), int(axis[0]*SCALE))
Dá pra usar f-strings

```suggestion
            txt = f"Linear: {int(axis[1]*SCALE)} Angular: {int(axis[0]*SCALE)}"
```

2021-04-18 17:46 UTC, LucasHaug commented on scripts/keyboard_node.py
> +            txt = "Linear: {} Angular: {}".format(int(vel_lin*SCALE), int(vel_ang*SCALE))
```suggestion
            txt = f"Linear: {int(vel_lin*SCALE)} Angular: {int(vel_ang*SCALE)}"
```

2021-04-18 17:46 UTC, LucasHaug commented on scripts/keyboard_node.py
> +            vel_cmd_twist.angular.z = vel_ang*MAX_ROT_VEL
```suggestion
            vel_cmd_twist.linear.x = vel_lin * MAX_LIN_VEL
            vel_cmd_twist.angular.z = vel_ang * MAX_ROT_VEL
```

2021-04-19 13:34 UTC, LucasHaug approved these changes, later dismissed
Vou deixar aprovado já, a única coisa que eu falaria seria pra usar f-strings em todo lugar que usa strings, não tem nada a ver com essa PR, então se quiser deixar assim e a gente mexer nisso quando for mexer na issue #18 que vai refatorar o script, acho de boas.

2021-04-20 00:22 UTC, GabrielCosme approved these changes

2021-04-20 00:25 UTC, LucasHaug approved these changes

2021-04-20 00:27 UTC, merged